name: Ramos
favicon: null
layout_spectrum: 0.49256322206929326
typography_spectrum: 0.9116789023391902
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4891666213516146
  lightness: 0.9184798507485539
  saturation: 0.18995824013836682
  rhythmicContrast: 0.17136277328245342
purpose: []
